services:
  mariadb:
    build: srcs/requirements/mariadb
    container_name: mariadb
    restart: no
    env_file:
    # - .env
      - .env.local # changer par .env pour correction
    volumes:
      - /home/rcochran/data/mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: srcs/requirements/wordpress/.
    container_name: wordpress
    restart: always
    env_file:
      # - .env
      - .env.local # changer par .env pour correction
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

  nginx:
    build: srcs/requirements/nginx/.
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: bind #ext4 #df -T /home/rcochran/data/mariadb
      device: /home/rcochran/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/rcochran/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge